# This workflow performs a static analysis of your Kotlin source code using Detekt.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. Manually, on demand, via the "workflow_dispatch" event

name: Scan with Detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
        gradle-home-cache-cleanup: true

    # Performs static analysis using Detekt
    - name: Run Detekt
      run: ./gradlew detekt

    # Uploads results to GitHub repository using the upload-sarif action
    - name: Upload detekt results
      uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
      if: always()
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: ${{ github.workspace }}/app/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}
