# This workflow performs a static analysis of your Kotlin source code using Detekt.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. Manually, on demand, via the "workflow_dispatch" event

name: Scan with Detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      with:
        gradle-home-cache-cleanup: true

    # Performs static analysis using Detekt
    - name: Run Detekt
      run: ./gradlew detekt

    # Uploads results to GitHub repository using the upload-sarif action
    - name: Upload detekt results
      uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      if: always()
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: ${{ github.workspace }}/app/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}
